### ISSUE TITLE
cxxflags are ordered differently on the command line for gcc and msvc

### ISSUE THREAD

**Issue by pdimov** [bfgroup/b2#137]
When one uses, e.g. `<cxxflags>-Wno-long-long`, for GCC and derived toolsets (e.g. `clang-linux`) the `-Wno-long-long` on the command line comes after the flags generated by the `<warnings>` option, e.g. `-Wall -Wextra -Wno-long-long`.

Under `msvc.jam` and derived toolsets such as `clang-win`, however, the order is reversed, e.g. `-Wno-long-long /W4`. The `/W4` option resets the warning state and `-Wno-long-long` is ignored.

I suspect that the reason for this is that in `gcc.jam`, `<cxxflags>` is declared as `USER_OPTIONS`:
https://github.com/bfgroup/b2/blob/b59e85fc762d71b0647fd04147957cf86f1873ef/src/tools/gcc.jam#L684-L686

In `msvc.jam`, though, it's declared as `C++FLAGS`:
https://github.com/bfgroup/b2/blob/b59e85fc762d71b0647fd04147957cf86f1873ef/src/tools/msvc.jam#L1959-L1960

Interestingly, `<asmflags>` in `msvc.jam` is `USER_ASMFLAGS`:
https://github.com/bfgroup/b2/blob/b59e85fc762d71b0647fd04147957cf86f1873ef/src/tools/msvc.jam#L1970

I don't know what the right fix is here, but I suspect the consistent thing to do would be to mark `<cflags>` as `USER_CFLAGS` and `<cxxflags>` as `USER_C++FLAGS`, assuming these things exist.

**Comment by grisumbras** [comment]
If the issue is with the ordering then simply changing the order of `$($(lang-flags))` and `$(OPTIONS)` here https://github.com/bfgroup/b2/blob/b59e85fc762d71b0647fd04147957cf86f1873ef/src/tools/msvc.jam#L1782
should solve it.

But I don't know if it would break anything else.

**Comment by pdimov** [comment]
See https://github.com/bfgroup/b2/pull/139.
