### ISSUE TITLE
Boost build fails when VS 2022 Preview is installed

### ISSUE THREAD

**Issue by pps83** [bfgroup/b2#391]
### Environment and version details

* Operating System+version: Win11 pro
* Compiler+version: VS 2022 Preview
* Shell: Batch
* B2 Version: B2 5.1.0 (OS=NT, jobs=8)

I've always used the same build command to build boost:
```
bootstrap
.\b2 address-model=32,64 variant=debug,release link=static threading=multi runtime-link=static stage
```

Today, I downloaded boost 1.85 and for the first time in many years build failed:

...
    - cxx20_hdr_concepts       : no [2]
    - cxx20_hdr_concepts       : no [3]
**error**: No best alternative for libs/context/build/asm_sources with <abi>ms <address-model>32 <asynch-exceptions>off <binary-format>pe <boost.cobalt.executor>any_io_executor <boost.cobalt.pmr>std <context-impl>fcontext <coverage>off <debug-store>object <debug-symbols>on <embed-manifest-via>linker <embed-manifest>on <exception-handling>on <extern-c-nothrow>off <inlining>off <link>static <midl-robust>yes <midl-stubless-proxy>yes <optimization>off <os>NT <pch>on <preserve-test-targets>on <profiling>off <python-debugging>off <relevant>abi <relevant>address-model <relevant>architecture <relevant>binary-format <relevant>toolset <rtti>on <runtime-debugging>on <runtime-link>static <stdlib>native <strip>off <target-os>windows <testing.execute>on <threadapi>win32 <threading>multi <toolset-msvc:version>14.3 <toolset>msvc <variant>debug <vectorize>off <visibility>hidden <warnings-as-errors>off <warnings>on <windows-api>desktop
    no match: <abi>aapcs <address-model>32 <architecture>arm <binary-format>elf <threading>multi <toolset>clang
    no match: <abi>aapcs <address-model>32 <architecture>arm <binary-format>elf <threading>multi <toolset>gcc
...

I tried all kinds of things, but it just always fails with that same error. Then, my suspicion was that boost build has issue with the `VS2022 Preview` and it seems to be the case: I downloaded boost 1.84 (that's the last version I have built locally with that same command I mentioned above). I tried to build 1.84 and I got exactly the same error, which makes me believe that boost build has some some sort of issue with `VS2022 Preview`. I have both VS2022 pro, and VS2022 Preview installed. Somewhat unusual perhaps about my install is that VS2022 is installed in `C:\` drive, while VS2022 Preview is installed in `D:\` drive.

Attached boost185-build.txt contains output when I tried to open vs2022 developer console and build: [boost185-build.txt](https://github.com/bfgroup/b2/files/15316609/boost185-build.txt). Same error happens if I opens vs2022 preview developer console, or plain cmd.exe

**Comment by dimitry-unified-streaming** [comment]
The minimal fix is:

```diff
diff --git a/src/tools/msvc.jam b/src/tools/msvc.jam
index f56f1cedb..7862e9988 100644
--- a/src/tools/msvc.jam
+++ b/src/tools/msvc.jam
@@ -1119,7 +1119,7 @@ local rule generate-setup-cmd ( version : command : parent : options * : cpu : g
         }
         else
         {
-            if [ MATCH "(14.3)" : $(version) ]
+            if [ MATCH "(14.[34])" : $(version) ]
             {
                 if $(.debug-configuration)
                 {
```

But ideally a new version `msvc-14.4` should be introduced, I guess. On the other hand, this is a case where a 'minor' update of Visual Studio 2022, namely going from v17.9 to v17.10, introduces a 'new' toolchain version starting with `14.40`.

E.g., I don't think there is a way to install both v17.9 and v17.10 side-by-side, so b2's `msvc-14.3` would still indicate "whatever the current version of Visual Studio 2022 is".

In that case, the fix above would probably be enough for the time being, until Microsoft releases e.g. Visual Studio 2024 and bumps the toolchain version to 14.5 or even 15.0 ...

@Kojoley @grafikrobot what's your opinion on this?

**Comment by pps83** [comment]
> But ideally a new version `msvc-14.4` should be introduced, I guess. On the other hand, this is a case where a 'minor' update of Visual Studio 2022, namely going from v17.9 to v17.10, introduces a 'new' toolchain version starting with `14.40`.

Not sure there is a version bump, but preview isn't a minor update.

**Comment by Kojoley** [comment]
> The (MSVC) toolset remains at version v143 in VS 17.10

Is it though? It tells its version as 14.40.33807.

**Comment by pdimov** [comment]
Yes, see the screenshots in https://devblogs.microsoft.com/cppblog/msvc-toolset-minor-version-number-14-40-in-vs-2022-v17-10/

**Comment by DimitryAndric** [comment]
Even though it identifies as 14.40.something, it still is a minor Visual Studio 2022 update, and it behaves exactly the same as the 14.39.* and 14.38.* versions before it. On the other hand, the blog Peter just pointed to seems to indicate that it might be possible to have both installed side-by-side?

**Comment by DimitryAndric** [comment]
Indeed, it looks like you can do that explicitly now (this is a screenshot of the Visual Studio Installer's "Individual components" tab):

<img width="461" alt="MSVC-installer" src="https://github.com/bfgroup/b2/assets/9060368/714374a5-9ee0-43e1-8c95-7d309f2a4cc2">

but I don't think b2 ever supported picking any of these fine-grained versions?

**Comment by pdimov** [comment]
Side by side is unrelated to this; you can also have 14.38 and 14.39 installed side by side. They are still all "platform toolset Visual Studio 2022 (v143)". (Whereas e.g. 14.24, which you can also have, is "platform toolset Visual Studio 2019 (v142)".

**Comment by Kojoley** [comment]
I cannot express my feelings about the version bullshit microsoft creates for every their product. The compiler already has like 3 distinct versions simultaneously, now we again have to square the circle.

**Comment by DimitryAndric** [comment]
Well, I just installed the "v14.39-17.9" component, and I now have both `14.39.33519` and `14.40.33807` in my MSVC directory:

```text
 Directory of  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\*

2024-05-23  17:00         <DIR>    14.39.33519
2024-05-23  15:21         <DIR>    14.40.33807
```

It looks like `msvc.jam` now chooses the first one, always. I don't see a way to tell it to use one or the other.

With `vcvars64.bat`, you can at least pass `-vcvars_ver=14.40.33807` to pick the one you want.

**Comment by pdimov** [comment]
> I don't see a way to tell it to use one or the other.

There has never been such a way and I've never missed it. We just need to tell b2 that 14.4x is still msvc-14.3 and be done with it.

**Comment by DimitryAndric** [comment]
Yes, I've submitted https://github.com/bfgroup/b2/pull/394 for this.
