### ISSUE TITLE
Failed to compile Boost library using MinGW GCC 13.2.0

### ISSUE THREAD

**Issue by Dinu5346** [bfgroup/b2#411]
### Make sure you completed the following tasks

- [✅] I searched the [discussions](https://github.com/bfgroup/b2/discussions)
- [✅] I searched the closed and open [issues](https://github.com/bfgroup/b2/issues?q=is%3Aissue)
- [✅] I read the [contribution guidelines](https://github.com/bfgroup/b2/blob/main/CONTRIBUTING.adoc)

### Environment and version details

* Operating System+version: **Windows 11  23H2 22631.4037**
* Compiler+version: **MinGW64 GCC 13.2.0**
* Shell: **Windows Command Prompt**
* B2 Version: 5.2.1
* B2 Configuration: 

```
notice: loading B2 from C:/b2-5.2.1/src/build-system.jam
notice: Searching 'C:\Windows' 'C:\Users\dinus' 'C:\Users\dinus' 'C:\b2-5.2.1\src\build' 'C:\b2-5.2.1\src\contrib' 'C:\b2-5.2.1\src\engine' 'C:\b2-5.2.1\src\options' 'C:\b2-5.2.1\src\tools' 'C:\b2-5.2.1\src\util' 'C:/b2-5.2.1/src' for site-config configuration file 'site-config.jam'.
notice: Configuration file 'site-config.jam' not found in 'C:\Windows' 'C:\Users\dinus' 'C:\Users\dinus' 'C:\b2-5.2.1\src\build' 'C:\b2-5.2.1\src\contrib' 'C:\b2-5.2.1\src\engine' 'C:\b2-5.2.1\src\options' 'C:\b2-5.2.1\src\tools' 'C:\b2-5.2.1\src\util' 'C:/b2-5.2.1/src'.
notice: Searching 'C:\Users\dinus' 'C:\Users\dinus' 'C:\b2-5.2.1\src\build' 'C:\b2-5.2.1\src\contrib' 'C:\b2-5.2.1\src\engine' 'C:\b2-5.2.1\src\options' 'C:\b2-5.2.1\src\tools' 'C:\b2-5.2.1\src\util' 'C:/b2-5.2.1/src' for user-config configuration file 'user-config.jam'.
notice: Configuration file 'user-config.jam' not found in 'C:\Users\dinus' 'C:\Users\dinus' 'C:\b2-5.2.1\src\build' 'C:\b2-5.2.1\src\contrib' 'C:\b2-5.2.1\src\engine' 'C:\b2-5.2.1\src\options' 'C:\b2-5.2.1\src\tools' 'C:\b2-5.2.1\src\util' 'C:/b2-5.2.1/src'.
Jamroot.jam:118: in modules.load from module Jamfile<C:\b2-5.2.1>
warning: Bison generator program 'bison' not found. Skipping grammar build.
C:/b2-5.2.1/src/build\project.jam:544: in load-jamfile from module project
C:/b2-5.2.1/src/build\project.jam:68: in load from module project
C:/b2-5.2.1/src/build\project.jam:201: in project.find from module project
C:/b2-5.2.1/src\build-system.jam:618: in module scope from module build-system
warning: No toolsets are configured.
warning: Configuring default toolset "msvc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: https://www.bfgroup.xyz/b2/manual/release/index.html#bbv2.overview.configuration
warning: toolset msvc initialization: can not find tool cl.exe
warning: initialized from

warning: Did not find command for MSVC toolset. If you have Visual Studio 2017 installed you will need to specify the full path to the command, set VS150COMNTOOLS for your installation, or build from the 'Visual Studio Command Prompt for VS 2017'.

notice: will use 'cl.exe' for msvc, condition <toolset>msvc-6.0
notice: [msvc-cfg] condition: '<toolset>msvc-6.0/<architecture>x86/<address-model>32', setup: ''
notice: [msvc-cfg] condition: '<toolset>msvc-6.0/<architecture>/<address-model>32', setup: ''
...found 1 target...
```

### Brief problem description
When I try to build Boost library using the command "b2 --build-dir="C:\Boost-5.2.1" --build-type=complete toolset=gcc-13.2.0 stage", it outputs some warnings and does not compile.

The output:
Jamroot.jam:118: in modules.load from module Jamfile<C:\b2-5.2.1>
warning: Bison generator program 'bison' not found. Skipping grammar build.
C:/b2-5.2.1/src/build\project.jam:544: in load-jamfile from module project
C:/b2-5.2.1/src/build\project.jam:68: in load from module project
C:/b2-5.2.1/src/build\project.jam:201: in project.find from module project
C:/b2-5.2.1/src\build-system.jam:618: in module scope from module build-system
...found 1 target...

### Steps to reproduce the issue
-Download Boost 5.2.1 source code zip from GitHub releases (https://github.com/bfgroup/b2/archive/refs/tags/5.2.1.zip)
-Extract it to the C: drive
-Build B2 using the command "bootstrap.bat mingw"
-Try to build Boost library using the command "b2 --build-dir="C:\Boost-5.2.1" --build-type=complete toolset=gcc-13.2.0 stage"

### Actual behavior summary

When I try to build Boost library using the command "b2 --build-dir="C:\Boost-5.2.1" --build-type=complete toolset=gcc-13.2.0 stage", it outputs some warnings and does not compile.

![image](https://github.com/user-attachments/assets/73da31d0-8d74-4aef-abdf-cebe84812269)

![image](https://github.com/user-attachments/assets/94d6ea5d-5fd7-4348-89d2-94638b209b5b)

### Expected behavior summary

Expected compiling process to continue and produce the output in the build directory

**Comment by grisumbras** [comment]
As far as I can see, you are not building Boost, you are building b2, which is the build system Boost uses. Official Boost releases can be found on this page: https://www.boost.org/users/download/. There are also (slightly less official) archives generated on GitHub: https://github.com/boostorg/boost/releases.
